development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Mongoid can connect to a URI accepted by the driver:
      uri: <%= ENV["MONGO_URL"] %>
test:
  clients:
    default:
      uri: <%= ENV["MONGO_URL"] %>
      